version: '3.2'
services:
  mysql_db:
    image: mysql:8.0.20
    volumes:
        - ./conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: test_ci
    networks:
      - dbnet
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE (https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log/55706057#55706057)

networks:
  dbnet:
    driver: bridge
