name: GE Releaser - Tag

on:
  workflow_dispatch:
    inputs:
      hash:
        description: "Git hash to tag (defaults to HEAD)"
        required: false
        default: "HEAD"
        type: string
      version:
        description: "Semantic version to tag"
        required: true
        type: string

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install ge_releaser
        run: pip install git+https://github.com/greatexpectationslabs/ge_releaser/
      - run: ge_releaser tag ${{ github.event.inputs.hash }} ${{ github.event.inputs.version }} --stable
